# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PICK GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1476, 784)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(200, 16))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setObjectName("Tabs")
        self.LogFileConfiguration = QtWidgets.QWidget()
        self.LogFileConfiguration.setObjectName("LogFileConfiguration")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.LogFileConfiguration)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logFileConfigCancelBut = QtWidgets.QPushButton(self.LogFileConfiguration)
        self.logFileConfigCancelBut.setObjectName("logFileConfigCancelBut")
        self.horizontalLayout.addWidget(self.logFileConfigCancelBut)
        self.logFileConfigValidBut = QtWidgets.QPushButton(self.LogFileConfiguration)
        self.logFileConfigValidBut.setObjectName("logFileConfigValidBut")
        self.horizontalLayout.addWidget(self.logFileConfigValidBut)
        self.logFileConfigEnforce = QtWidgets.QPushButton(self.LogFileConfiguration)
        self.logFileConfigEnforce.setObjectName("logFileConfigEnforce")
        self.horizontalLayout.addWidget(self.logFileConfigEnforce)
        self.gridLayout_5.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.logFileConfiguration = QtWidgets.QLabel(self.LogFileConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logFileConfiguration.setFont(font)
        self.logFileConfiguration.setAlignment(QtCore.Qt.AlignCenter)
        self.logFileConfiguration.setObjectName("logFileConfiguration")
        self.gridLayout_5.addWidget(self.logFileConfiguration, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logFileConfigfileName = QtWidgets.QLabel(self.LogFileConfiguration)
        self.logFileConfigfileName.setObjectName("logFileConfigfileName")
        self.horizontalLayout_2.addWidget(self.logFileConfigfileName)
        self.logFileConfigName = QtWidgets.QLabel(self.LogFileConfiguration)
        self.logFileConfigName.setObjectName("logFileConfigName")
        self.horizontalLayout_2.addWidget(self.logFileConfigName)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.logFileErrorsTable = QtWidgets.QTableWidget(self.LogFileConfiguration)
        self.logFileErrorsTable.setObjectName("logFileErrorsTable")
        self.logFileErrorsTable.setColumnCount(3)
        self.logFileErrorsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.logFileErrorsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileErrorsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileErrorsTable.setHorizontalHeaderItem(2, item)
        self.gridLayout_5.addWidget(self.logFileErrorsTable, 1, 0, 1, 1)
        self.logFileTable = QtWidgets.QTableWidget(self.LogFileConfiguration)
        self.logFileTable.setObjectName("logFileTable")
        self.logFileTable.setColumnCount(5)
        self.logFileTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.logFileTable.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.logFileTable, 4, 0, 1, 1)
        self.Tabs.addTab(self.LogFileConfiguration, "")
        self.LogEntryConfiguration = QtWidgets.QWidget()
        self.LogEntryConfiguration.setAccessibleName("")
        self.LogEntryConfiguration.setProperty("page", "")
        self.LogEntryConfiguration.setObjectName("LogEntryConfiguration")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LogEntryConfiguration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LogEntryLabel = QtWidgets.QLabel(self.LogEntryConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LogEntryLabel.setFont(font)
        self.LogEntryLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.LogEntryLabel.setObjectName("LogEntryLabel")
        self.verticalLayout.addWidget(self.LogEntryLabel)
        self.LogEntryFilterBut = QtWidgets.QPushButton(self.LogEntryConfiguration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LogEntryFilterBut.setFont(font)
        self.LogEntryFilterBut.setObjectName("LogEntryFilterBut")
        self.verticalLayout.addWidget(self.LogEntryFilterBut, 0, QtCore.Qt.AlignLeft)
        self.LogEntryTable = QtWidgets.QTableWidget(self.LogEntryConfiguration)
        self.LogEntryTable.setObjectName("LogEntryTable")
        self.LogEntryTable.setColumnCount(4)
        self.LogEntryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntryTable.setHorizontalHeaderItem(3, item)
        self.LogEntryTable.horizontalHeader().setCascadingSectionResizes(True)
        self.LogEntryTable.horizontalHeader().setDefaultSectionSize(150)
        self.LogEntryTable.horizontalHeader().setMinimumSectionSize(40)
        self.LogEntryTable.horizontalHeader().setStretchLastSection(False)
        self.LogEntryTable.verticalHeader().setCascadingSectionResizes(True)
        self.LogEntryTable.verticalHeader().setDefaultSectionSize(50)
        self.LogEntryTable.verticalHeader().setMinimumSectionSize(40)
        self.verticalLayout.addWidget(self.LogEntryTable)
        self.Tabs.addTab(self.LogEntryConfiguration, "")
        self.VectorConfiguration = QtWidgets.QWidget()
        self.VectorConfiguration.setObjectName("VectorConfiguration")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.VectorConfiguration)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VectorConfigLabel = QtWidgets.QLabel(self.VectorConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.VectorConfigLabel.setFont(font)
        self.VectorConfigLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.VectorConfigLabel.setObjectName("VectorConfigLabel")
        self.verticalLayout_3.addWidget(self.VectorConfigLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.VectorConfigAddVectorBut = QtWidgets.QPushButton(self.VectorConfiguration)
        self.VectorConfigAddVectorBut.setObjectName("VectorConfigAddVectorBut")
        self.horizontalLayout_3.addWidget(self.VectorConfigAddVectorBut)
        self.VectorConfigDeleteVectorBut = QtWidgets.QPushButton(self.VectorConfiguration)
        self.VectorConfigDeleteVectorBut.setObjectName("VectorConfigDeleteVectorBut")
        self.horizontalLayout_3.addWidget(self.VectorConfigDeleteVectorBut)
        self.VectorConfigEditVectorBut = QtWidgets.QPushButton(self.VectorConfiguration)
        self.VectorConfigEditVectorBut.setObjectName("VectorConfigEditVectorBut")
        self.horizontalLayout_3.addWidget(self.VectorConfigEditVectorBut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.VectorConfigTable = QtWidgets.QTableWidget(self.VectorConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.VectorConfigTable.sizePolicy().hasHeightForWidth())
        self.VectorConfigTable.setSizePolicy(sizePolicy)
        self.VectorConfigTable.setTabletTracking(False)
        self.VectorConfigTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.VectorConfigTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.VectorConfigTable.setWordWrap(True)
        self.VectorConfigTable.setColumnCount(3)
        self.VectorConfigTable.setObjectName("VectorConfigTable")
        self.VectorConfigTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.VectorConfigTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorConfigTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorConfigTable.setHorizontalHeaderItem(2, item)
        self.VectorConfigTable.horizontalHeader().setCascadingSectionResizes(True)
        self.VectorConfigTable.horizontalHeader().setDefaultSectionSize(150)
        self.VectorConfigTable.horizontalHeader().setMinimumSectionSize(50)
        self.VectorConfigTable.horizontalHeader().setStretchLastSection(True)
        self.VectorConfigTable.verticalHeader().setSortIndicatorShown(True)
        self.VectorConfigTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.VectorConfigTable)
        self.Tabs.addTab(self.VectorConfiguration, "")
        self.VectorDB = QtWidgets.QWidget()
        self.VectorDB.setObjectName("VectorDB")
        self.gridLayout = QtWidgets.QGridLayout(self.VectorDB)
        self.gridLayout.setObjectName("gridLayout")
        self.VectoDBPullBut = QtWidgets.QPushButton(self.VectorDB)
        self.VectoDBPullBut.setObjectName("VectoDBPullBut")
        self.gridLayout.addWidget(self.VectoDBPullBut, 2, 0, 1, 1)
        self.VectorDBchangesTable = QtWidgets.QTableWidget(self.VectorDB)
        self.VectorDBchangesTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.VectorDBchangesTable.setFont(font)
        self.VectorDBchangesTable.setMouseTracking(True)
        self.VectorDBchangesTable.setTabletTracking(True)
        self.VectorDBchangesTable.setAutoFillBackground(False)
        self.VectorDBchangesTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.VectorDBchangesTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.VectorDBchangesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.VectorDBchangesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.VectorDBchangesTable.setWordWrap(True)
        self.VectorDBchangesTable.setObjectName("VectorDBchangesTable")
        self.VectorDBchangesTable.setColumnCount(8)
        self.VectorDBchangesTable.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBchangesTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBchangesTable.setItem(10, 0, item)
        self.VectorDBchangesTable.horizontalHeader().setVisible(True)
        self.VectorDBchangesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.VectorDBchangesTable.horizontalHeader().setDefaultSectionSize(150)
        self.VectorDBchangesTable.horizontalHeader().setHighlightSections(False)
        self.VectorDBchangesTable.horizontalHeader().setMinimumSectionSize(25)
        self.VectorDBchangesTable.horizontalHeader().setSortIndicatorShown(True)
        self.VectorDBchangesTable.horizontalHeader().setStretchLastSection(True)
        self.VectorDBchangesTable.verticalHeader().setVisible(False)
        self.VectorDBchangesTable.verticalHeader().setDefaultSectionSize(35)
        self.VectorDBchangesTable.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.VectorDBchangesTable, 6, 0, 1, 2)
        self.VectorDBApprovalLabel = QtWidgets.QLabel(self.VectorDB)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.VectorDBApprovalLabel.setFont(font)
        self.VectorDBApprovalLabel.setObjectName("VectorDBApprovalLabel")
        self.gridLayout.addWidget(self.VectorDBApprovalLabel, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VectorDBPushTable = QtWidgets.QTableWidget(self.VectorDB)
        self.VectorDBPushTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.VectorDBPushTable.setFont(font)
        self.VectorDBPushTable.setMouseTracking(True)
        self.VectorDBPushTable.setTabletTracking(True)
        self.VectorDBPushTable.setAutoFillBackground(False)
        self.VectorDBPushTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.VectorDBPushTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.VectorDBPushTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.VectorDBPushTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.VectorDBPushTable.setWordWrap(True)
        self.VectorDBPushTable.setObjectName("VectorDBPushTable")
        self.VectorDBPushTable.setColumnCount(4)
        self.VectorDBPushTable.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPushTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPushTable.setItem(10, 0, item)
        self.VectorDBPushTable.horizontalHeader().setVisible(True)
        self.VectorDBPushTable.horizontalHeader().setCascadingSectionResizes(True)
        self.VectorDBPushTable.horizontalHeader().setDefaultSectionSize(150)
        self.VectorDBPushTable.horizontalHeader().setHighlightSections(False)
        self.VectorDBPushTable.horizontalHeader().setMinimumSectionSize(25)
        self.VectorDBPushTable.horizontalHeader().setSortIndicatorShown(True)
        self.VectorDBPushTable.horizontalHeader().setStretchLastSection(True)
        self.VectorDBPushTable.verticalHeader().setVisible(False)
        self.VectorDBPushTable.verticalHeader().setDefaultSectionSize(35)
        self.VectorDBPushTable.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.VectorDBPushTable, 3, 1, 1, 1)
        self.VectorDBPushedVecLabel = QtWidgets.QLabel(self.VectorDB)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.VectorDBPushedVecLabel.setFont(font)
        self.VectorDBPushedVecLabel.setObjectName("VectorDBPushedVecLabel")
        self.gridLayout.addWidget(self.VectorDBPushedVecLabel, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.VectoDBPushBut = QtWidgets.QPushButton(self.VectorDB)
        self.VectoDBPushBut.setObjectName("VectoDBPushBut")
        self.gridLayout.addWidget(self.VectoDBPushBut, 2, 1, 1, 1)
        self.VectorDBCommitBut = QtWidgets.QPushButton(self.VectorDB)
        self.VectorDBCommitBut.setObjectName("VectorDBCommitBut")
        self.gridLayout.addWidget(self.VectorDBCommitBut, 5, 0, 1, 1)
        self.VectorDBPulledVecLabel = QtWidgets.QLabel(self.VectorDB)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.VectorDBPulledVecLabel.setFont(font)
        self.VectorDBPulledVecLabel.setObjectName("VectorDBPulledVecLabel")
        self.gridLayout.addWidget(self.VectorDBPulledVecLabel, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VectorDBPullTable = QtWidgets.QTableWidget(self.VectorDB)
        self.VectorDBPullTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.VectorDBPullTable.setFont(font)
        self.VectorDBPullTable.setMouseTracking(True)
        self.VectorDBPullTable.setTabletTracking(True)
        self.VectorDBPullTable.setAutoFillBackground(False)
        self.VectorDBPullTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.VectorDBPullTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.VectorDBPullTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.VectorDBPullTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.VectorDBPullTable.setWordWrap(True)
        self.VectorDBPullTable.setObjectName("VectorDBPullTable")
        self.VectorDBPullTable.setColumnCount(4)
        self.VectorDBPullTable.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorDBPullTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.VectorDBPullTable.setItem(10, 0, item)
        self.VectorDBPullTable.horizontalHeader().setVisible(True)
        self.VectorDBPullTable.horizontalHeader().setCascadingSectionResizes(True)
        self.VectorDBPullTable.horizontalHeader().setDefaultSectionSize(150)
        self.VectorDBPullTable.horizontalHeader().setHighlightSections(False)
        self.VectorDBPullTable.horizontalHeader().setMinimumSectionSize(25)
        self.VectorDBPullTable.horizontalHeader().setSortIndicatorShown(True)
        self.VectorDBPullTable.horizontalHeader().setStretchLastSection(True)
        self.VectorDBPullTable.verticalHeader().setVisible(False)
        self.VectorDBPullTable.verticalHeader().setDefaultSectionSize(35)
        self.VectorDBPullTable.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.VectorDBPullTable, 3, 0, 1, 1)
        self.VectorDBConnectionLabel = QtWidgets.QLabel(self.VectorDB)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.VectorDBConnectionLabel.setFont(font)
        self.VectorDBConnectionLabel.setObjectName("VectorDBConnectionLabel")
        self.gridLayout.addWidget(self.VectorDBConnectionLabel, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.Tabs.addTab(self.VectorDB, "")
        self.RelConfig = QtWidgets.QWidget()
        self.RelConfig.setObjectName("RelConfig")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.RelConfig)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.RelationshipConfigLabel = QtWidgets.QLabel(self.RelConfig)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RelationshipConfigLabel.setFont(font)
        self.RelationshipConfigLabel.setObjectName("RelationshipConfigLabel")
        self.verticalLayout_5.addWidget(self.RelationshipConfigLabel, 0, QtCore.Qt.AlignHCenter)
        self.RelationConfigTable = QtWidgets.QTableWidget(self.RelConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RelationConfigTable.sizePolicy().hasHeightForWidth())
        self.RelationConfigTable.setSizePolicy(sizePolicy)
        self.RelationConfigTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.RelationConfigTable.setFont(font)
        self.RelationConfigTable.setMouseTracking(True)
        self.RelationConfigTable.setTabletTracking(True)
        self.RelationConfigTable.setAutoFillBackground(False)
        self.RelationConfigTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.RelationConfigTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.RelationConfigTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.RelationConfigTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.RelationConfigTable.setWordWrap(True)
        self.RelationConfigTable.setObjectName("RelationConfigTable")
        self.RelationConfigTable.setColumnCount(5)
        self.RelationConfigTable.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RelationConfigTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.RelationConfigTable.setItem(10, 0, item)
        self.RelationConfigTable.horizontalHeader().setVisible(True)
        self.RelationConfigTable.horizontalHeader().setCascadingSectionResizes(True)
        self.RelationConfigTable.horizontalHeader().setDefaultSectionSize(250)
        self.RelationConfigTable.horizontalHeader().setHighlightSections(False)
        self.RelationConfigTable.horizontalHeader().setMinimumSectionSize(25)
        self.RelationConfigTable.horizontalHeader().setSortIndicatorShown(True)
        self.RelationConfigTable.horizontalHeader().setStretchLastSection(False)
        self.RelationConfigTable.verticalHeader().setVisible(False)
        self.RelationConfigTable.verticalHeader().setDefaultSectionSize(35)
        self.RelationConfigTable.verticalHeader().setHighlightSections(False)
        self.RelationConfigTable.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_5.addWidget(self.RelationConfigTable)
        self.Tabs.addTab(self.RelConfig, "")
        
        self.GraphView = QtWidgets.QWidget()
        self.GraphView.setObjectName("GraphView")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GraphView)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        
        self.GraphViewGraphPlace = QtWidgets.QGraphicsView(self.GraphView)
        self.GraphViewGraphPlace.setObjectName("GraphViewGraphPlace")
        self.gridLayout_3.addWidget(self.GraphViewGraphPlace, 2, 5, 10, 1)
        
        
        self.GraphViewNodesLabel = QtWidgets.QLabel(self.GraphView)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.GraphViewNodesLabel.setFont(font)
        self.GraphViewNodesLabel.setObjectName("GraphViewNodesLabel")
        self.gridLayout_3.addWidget(self.GraphViewNodesLabel, 0, 2, 1, 4)
        self.GraphViewTimeLineOption = QtWidgets.QComboBox(self.GraphView)
        self.GraphViewTimeLineOption.setObjectName("GraphViewTimeLineOption")
        self.GraphViewTimeLineOption.addItem("")
        self.GraphViewTimeLineOption.addItem("")
        self.gridLayout_3.addWidget(self.GraphViewTimeLineOption, 2, 0, 1, 3)
        self.GraphViewVectorOptions = QtWidgets.QComboBox(self.GraphView)
        self.GraphViewVectorOptions.setObjectName("GraphViewVectorOptions")
        self.GraphViewVectorOptions.addItem("")
        self.GraphViewVectorOptions.addItem("")
        self.gridLayout_3.addWidget(self.GraphViewVectorOptions, 7, 1, 1, 2)
        self.GraphViewAddNodeBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewAddNodeBut.setObjectName("GraphViewAddNodeBut")
        self.gridLayout_3.addWidget(self.GraphViewAddNodeBut, 9, 0, 1, 2)
        self.GraphViewAddRelationshipBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewAddRelationshipBut.setObjectName("GraphViewAddRelationshipBut")
        self.gridLayout_3.addWidget(self.GraphViewAddRelationshipBut, 9, 2, 1, 1)
        self.GraphViewEditNodeBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewEditNodeBut.setObjectName("GraphViewEditNodeBut")
        self.gridLayout_3.addWidget(self.GraphViewEditNodeBut, 9, 3, 1, 2)
        self.GraphViewGraphConfigLabel = QtWidgets.QLabel(self.GraphView)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.GraphViewGraphConfigLabel.setFont(font)
        self.GraphViewGraphConfigLabel.setObjectName("GraphViewGraphConfigLabel")
        self.gridLayout_3.addWidget(self.GraphViewGraphConfigLabel, 5, 0, 1, 3)
        self.GraphViewDeleteNodeBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewDeleteNodeBut.setObjectName("GraphViewDeleteNodeBut")
        self.gridLayout_3.addWidget(self.GraphViewDeleteNodeBut, 10, 0, 1, 2)
        self.GraphViewRemRelationshipBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewRemRelationshipBut.setObjectName("GraphViewRemRelationshipBut")
        self.gridLayout_3.addWidget(self.GraphViewRemRelationshipBut, 10, 2, 1, 1)
        self.GraphViewIconConfigBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewIconConfigBut.setObjectName("GraphViewIconConfigBut")
        self.gridLayout_3.addWidget(self.GraphViewIconConfigBut, 5, 4, 1, 1)
        self.GraphViewIntervalOptions = QtWidgets.QComboBox(self.GraphView)
        self.GraphViewIntervalOptions.setObjectName("GraphViewIntervalOptions")
        self.GraphViewIntervalOptions.addItem("")
        self.GraphViewIntervalOptions.addItem("")
        self.gridLayout_3.addWidget(self.GraphViewIntervalOptions, 4, 0, 1, 3)
        self.GraphViewTimelineLabel = QtWidgets.QLabel(self.GraphView)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GraphViewTimelineLabel.setFont(font)
        self.GraphViewTimelineLabel.setObjectName("GraphViewTimelineLabel")
        self.gridLayout_3.addWidget(self.GraphViewTimelineLabel, 1, 0, 1, 3)
        self.GraphViewZoomOutBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewZoomOutBut.setObjectName("GraphViewZoomOutBut")
        self.gridLayout_3.addWidget(self.GraphViewZoomOutBut, 3, 4, 2, 1)
        self.GraphViewDescriptionLabel = QtWidgets.QLabel(self.GraphView)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GraphViewDescriptionLabel.setFont(font)
        self.GraphViewDescriptionLabel.setObjectName("GraphViewDescriptionLabel")
        self.gridLayout_3.addWidget(self.GraphViewDescriptionLabel, 8, 0, 1, 2)
        self.GraphViewEditRelationshipBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewEditRelationshipBut.setObjectName("GraphViewEditRelationshipBut")
        self.gridLayout_3.addWidget(self.GraphViewEditRelationshipBut, 10, 3, 1, 2)
        self.GraphViewIntervalLabel = QtWidgets.QLabel(self.GraphView)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GraphViewIntervalLabel.setFont(font)
        self.GraphViewIntervalLabel.setObjectName("GraphViewIntervalLabel")
        self.gridLayout_3.addWidget(self.GraphViewIntervalLabel, 3, 0, 1, 3)
        self.GraphViewVectorLabel = QtWidgets.QLabel(self.GraphView)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GraphViewVectorLabel.setFont(font)
        self.GraphViewVectorLabel.setObjectName("GraphViewVectorLabel")
        self.gridLayout_3.addWidget(self.GraphViewVectorLabel, 6, 0, 2, 3)
        self.GraphViewDescriptionTextBox = QtWidgets.QPlainTextEdit(self.GraphView)
        self.GraphViewDescriptionTextBox.setObjectName("GraphViewDescriptionTextBox")
        self.gridLayout_3.addWidget(self.GraphViewDescriptionTextBox, 8, 2, 1, 2)
        self.GraphViewZoomInBut = QtWidgets.QPushButton(self.GraphView)
        self.GraphViewZoomInBut.setObjectName("GraphViewZoomInBut")
        self.gridLayout_3.addWidget(self.GraphViewZoomInBut, 1, 4, 2, 1)
        self.Tabs.addTab(self.GraphView, "")
        self.TableView = QtWidgets.QWidget()
        self.TableView.setObjectName("TableView")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.TableView)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TableViewLabel = QtWidgets.QLabel(self.TableView)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TableViewLabel.setFont(font)
        self.TableViewLabel.setObjectName("TableViewLabel")
        self.verticalLayout_4.addWidget(self.TableViewLabel, 0, QtCore.Qt.AlignHCenter)
        self.TableViewTable = QtWidgets.QTableWidget(self.TableView)
        self.TableViewTable.setMinimumSize(QtCore.QSize(1028, 422))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.TableViewTable.setFont(font)
        self.TableViewTable.setMouseTracking(True)
        self.TableViewTable.setTabletTracking(True)
        self.TableViewTable.setAutoFillBackground(False)
        self.TableViewTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.TableViewTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TableViewTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TableViewTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TableViewTable.setWordWrap(True)
        self.TableViewTable.setObjectName("TableViewTable")
        self.TableViewTable.setColumnCount(11)
        self.TableViewTable.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.TableViewTable.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()



        self.TableViewTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableViewTable.setItem(2, 10, item)

        self.TableViewTable.horizontalHeader().setVisible(True)
        self.TableViewTable.horizontalHeader().setCascadingSectionResizes(True)
        self.TableViewTable.horizontalHeader().setDefaultSectionSize(150)
        self.TableViewTable.horizontalHeader().setHighlightSections(False)
        self.TableViewTable.horizontalHeader().setMinimumSectionSize(25)
        self.TableViewTable.horizontalHeader().setSortIndicatorShown(True)
        self.TableViewTable.horizontalHeader().setStretchLastSection(False)
        self.TableViewTable.verticalHeader().setVisible(False)
        self.TableViewTable.verticalHeader().setDefaultSectionSize(35)
        self.TableViewTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.TableViewTable)
        self.Tabs.addTab(self.TableView, "")
        self.DoubleView = QtWidgets.QWidget()
        self.DoubleView.setObjectName("DoubleView")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.DoubleView)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DoubleViewVectorLabel = QtWidgets.QLabel(self.DoubleView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DoubleViewVectorLabel.sizePolicy().hasHeightForWidth())
        self.DoubleViewVectorLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DoubleViewVectorLabel.setFont(font)
        self.DoubleViewVectorLabel.setObjectName("DoubleViewVectorLabel")
        self.gridLayout_4.addWidget(self.DoubleViewVectorLabel, 6, 0, 1, 1)
        
        
        self.DoubleViewGraphicsPlace = QtWidgets.QGraphicsView(self.DoubleView)
        self.DoubleViewGraphicsPlace.setObjectName("DoubleViewGraphicsPlace")
        self.gridLayout_4.addWidget(self.DoubleViewGraphicsPlace, 0, 3, 6, 1)
        
        
        self.DoubleViewZoomInBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewZoomInBut.setObjectName("DoubleViewZoomInBut")
        self.gridLayout_4.addWidget(self.DoubleViewZoomInBut, 1, 1, 1, 1)
        self.DoubleViewIntervalOptions = QtWidgets.QComboBox(self.DoubleView)
        self.DoubleViewIntervalOptions.setObjectName("DoubleViewIntervalOptions")
        self.DoubleViewIntervalOptions.addItem("")
        self.DoubleViewIntervalOptions.addItem("")
        self.gridLayout_4.addWidget(self.DoubleViewIntervalOptions, 4, 0, 1, 1)
        self.DoubleViewEditRelationshipBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewEditRelationshipBut.setObjectName("DoubleViewEditRelationshipBut")
        self.gridLayout_4.addWidget(self.DoubleViewEditRelationshipBut, 5, 1, 1, 1)
        self.DoubleViewZoomOutBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewZoomOutBut.setObjectName("DoubleViewZoomOutBut")
        self.gridLayout_4.addWidget(self.DoubleViewZoomOutBut, 2, 1, 1, 1)
        self.DoubleViewIntervalUnitsLabel = QtWidgets.QLabel(self.DoubleView)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DoubleViewIntervalUnitsLabel.setFont(font)
        self.DoubleViewIntervalUnitsLabel.setObjectName("DoubleViewIntervalUnitsLabel")
        self.gridLayout_4.addWidget(self.DoubleViewIntervalUnitsLabel, 3, 0, 1, 1)
        self.DoubleViewDescriptionLabel = QtWidgets.QLabel(self.DoubleView)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DoubleViewDescriptionLabel.setFont(font)
        self.DoubleViewDescriptionLabel.setScaledContents(False)
        self.DoubleViewDescriptionLabel.setObjectName("DoubleViewDescriptionLabel")
        self.gridLayout_4.addWidget(self.DoubleViewDescriptionLabel, 8, 0, 1, 1)
        self.DoubleViewAddRelationshipBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewAddRelationshipBut.setObjectName("DoubleViewAddRelationshipBut")
        self.gridLayout_4.addWidget(self.DoubleViewAddRelationshipBut, 10, 1, 1, 1)
        self.DoubleViewIconConfigBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewIconConfigBut.setObjectName("DoubleViewIconConfigBut")
        self.gridLayout_4.addWidget(self.DoubleViewIconConfigBut, 3, 1, 1, 1)
        self.DoubleViewTable = QtWidgets.QTableWidget(self.DoubleView)
        self.DoubleViewTable.setMinimumSize(QtCore.QSize(1028, 422))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.DoubleViewTable.setFont(font)
        self.DoubleViewTable.setMouseTracking(True)
        self.DoubleViewTable.setTabletTracking(True)
        self.DoubleViewTable.setAutoFillBackground(False)
        self.DoubleViewTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.DoubleViewTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.DoubleViewTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.DoubleViewTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.DoubleViewTable.setWordWrap(True)
        self.DoubleViewTable.setObjectName("DoubleViewTable")
        self.DoubleViewTable.setColumnCount(11)
        self.DoubleViewTable.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.DoubleViewTable.setItem(10, 0, item)

        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoubleViewTable.setItem(2, 10, item)
        self.DoubleViewTable.horizontalHeader().setVisible(True)
        self.DoubleViewTable.horizontalHeader().setCascadingSectionResizes(True)
        self.DoubleViewTable.horizontalHeader().setDefaultSectionSize(150)
        self.DoubleViewTable.horizontalHeader().setHighlightSections(False)
        self.DoubleViewTable.horizontalHeader().setMinimumSectionSize(25)
        self.DoubleViewTable.horizontalHeader().setSortIndicatorShown(True)
        self.DoubleViewTable.horizontalHeader().setStretchLastSection(False)
        self.DoubleViewTable.verticalHeader().setVisible(False)
        self.DoubleViewTable.verticalHeader().setDefaultSectionSize(35)
        self.DoubleViewTable.verticalHeader().setHighlightSections(False)
        self.gridLayout_4.addWidget(self.DoubleViewTable, 6, 3, 5, 1)
        self.GraphConfi = QtWidgets.QLabel(self.DoubleView)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.GraphConfi.setFont(font)
        self.GraphConfi.setObjectName("GraphConfi")
        self.gridLayout_4.addWidget(self.GraphConfi, 5, 0, 1, 1)
        self.DoubleViewVectorOptions = QtWidgets.QComboBox(self.DoubleView)
        self.DoubleViewVectorOptions.setObjectName("DoubleViewVectorOptions")
        self.DoubleViewVectorOptions.addItem("")
        self.DoubleViewVectorOptions.addItem("")
        self.gridLayout_4.addWidget(self.DoubleViewVectorOptions, 7, 0, 1, 1)
        self.DoubleViewTimelineOptions = QtWidgets.QComboBox(self.DoubleView)
        self.DoubleViewTimelineOptions.setObjectName("DoubleViewTimelineOptions")
        self.DoubleViewTimelineOptions.addItem("")
        self.DoubleViewTimelineOptions.addItem("")
        self.gridLayout_4.addWidget(self.DoubleViewTimelineOptions, 1, 0, 1, 1)
        self.DoubleViewRemoveRelationshipBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewRemoveRelationshipBut.setObjectName("DoubleViewRemoveRelationshipBut")
        self.gridLayout_4.addWidget(self.DoubleViewRemoveRelationshipBut, 11, 1, 1, 1)
        self.DoubleViewEditNodeBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewEditNodeBut.setObjectName("DoubleViewEditNodeBut")
        self.gridLayout_4.addWidget(self.DoubleViewEditNodeBut, 4, 1, 1, 1)
        self.DoubleViewAddNodeBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewAddNodeBut.setObjectName("DoubleViewAddNodeBut")
        self.gridLayout_4.addWidget(self.DoubleViewAddNodeBut, 10, 0, 1, 1)
        self.DoubleViewDescriptionTextbox = QtWidgets.QPlainTextEdit(self.DoubleView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.DoubleViewDescriptionTextbox.sizePolicy().hasHeightForWidth())
        self.DoubleViewDescriptionTextbox.setSizePolicy(sizePolicy)
        self.DoubleViewDescriptionTextbox.setObjectName("DoubleViewDescriptionTextbox")
        self.gridLayout_4.addWidget(self.DoubleViewDescriptionTextbox, 9, 0, 1, 1)
        self.DoubleViewTimelineLabel = QtWidgets.QLabel(self.DoubleView)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DoubleViewTimelineLabel.setFont(font)
        self.DoubleViewTimelineLabel.setObjectName("DoubleViewTimelineLabel")
        self.gridLayout_4.addWidget(self.DoubleViewTimelineLabel, 0, 0, 1, 1)
        self.DoubleViewDeleteNodeBut = QtWidgets.QPushButton(self.DoubleView)
        self.DoubleViewDeleteNodeBut.setObjectName("DoubleViewDeleteNodeBut")
        self.gridLayout_4.addWidget(self.DoubleViewDeleteNodeBut, 11, 0, 1, 1)
        self.Tabs.addTab(self.DoubleView, "")
        self.gridLayout_2.addWidget(self.Tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1476, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.Export = QtWidgets.QMenu(self.menuFile)
        self.Export.setObjectName("Export")
        self.menuGraph_Export_Options = QtWidgets.QMenu(self.Export)
        self.menuGraph_Export_Options.setObjectName("menuGraph_Export_Options")
        self.menuTable_Export_Options = QtWidgets.QMenu(self.Export)
        self.menuTable_Export_Options.setObjectName("menuTable_Export_Options")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.Save = QtWidgets.QAction(MainWindow)
        self.Save.setObjectName("Save")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionJPEG = QtWidgets.QAction(MainWindow)
        self.actionJPEG.setObjectName("actionJPEG")
        self.actionPNG = QtWidgets.QAction(MainWindow)
        self.actionPNG.setObjectName("actionPNG")
        self.actionView_Vector = QtWidgets.QAction(MainWindow)
        self.actionView_Vector.setObjectName("actionView_Vector")
        self.actionView_Table = QtWidgets.QAction(MainWindow)
        self.actionView_Table.setObjectName("actionView_Table")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCommit = QtWidgets.QAction(MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionChange_list = QtWidgets.QAction(MainWindow)
        self.actionChange_list.setObjectName("actionChange_list")
        self.actionEvent_Configuration = QtWidgets.QAction(MainWindow)
        self.actionEvent_Configuration.setObjectName("actionEvent_Configuration")
        self.actionDir_Configuration = QtWidgets.QAction(MainWindow)
        self.actionDir_Configuration.setObjectName("actionDir_Configuration")
        self.actionTeam_Configuration = QtWidgets.QAction(MainWindow)
        self.actionTeam_Configuration.setObjectName("actionTeam_Configuration")
        self.actionEvent_Configuration_2 = QtWidgets.QAction(MainWindow)
        self.actionEvent_Configuration_2.setObjectName("actionEvent_Configuration_2")
        self.actionPNG_2 = QtWidgets.QAction(MainWindow)
        self.actionPNG_2.setObjectName("actionPNG_2")
        self.actionJPEG_2 = QtWidgets.QAction(MainWindow)
        self.actionJPEG_2.setObjectName("actionJPEG_2")
        self.actionCSV = QtWidgets.QAction(MainWindow)
        self.actionCSV.setObjectName("actionCSV")
        self.actionExcel = QtWidgets.QAction(MainWindow)
        self.actionExcel.setObjectName("actionExcel")
        self.actionPDF = QtWidgets.QAction(MainWindow)
        self.actionPDF.setObjectName("actionPDF")
        self.menuGraph_Export_Options.addAction(self.actionPNG_2)
        self.menuGraph_Export_Options.addAction(self.actionJPEG_2)
        self.menuTable_Export_Options.addAction(self.actionCSV)
        self.menuTable_Export_Options.addAction(self.actionExcel)
        self.menuTable_Export_Options.addAction(self.actionPDF)
        self.Export.addAction(self.menuGraph_Export_Options.menuAction())
        self.Export.addAction(self.menuTable_Export_Options.menuAction())
        self.menuFile.addAction(self.Save)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.Export.menuAction())
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCommit)
        self.menuEdit.addAction(self.actionChange_list)
        self.menuEdit.addAction(self.actionEvent_Configuration_2)
        self.menuEdit.addAction(self.actionDir_Configuration)
        self.menuEdit.addAction(self.actionTeam_Configuration)
        self.menuView.addAction(self.actionView_Vector)
        self.menuView.addAction(self.actionView_Table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Status: Connected"))
        self.Tabs.setToolTip(_translate("MainWindow", "<html><head/><body><p>dvfas</p></body></html>"))
        self.logFileConfigCancelBut.setText(_translate("MainWindow", "Cancel"))
        self.logFileConfigValidBut.setText(_translate("MainWindow", "Validate"))
        self.logFileConfigEnforce.setText(_translate("MainWindow", "View Enforcement Report"))
        self.logFileConfiguration.setText(_translate("MainWindow", "Log File Configuration"))
        self.logFileConfigfileName.setText(_translate("MainWindow", "File Name:"))
        self.logFileConfigName.setText(_translate("MainWindow", "Name of Selected Log File"))
        item = self.logFileErrorsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.logFileErrorsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Line Number"))
        item = self.logFileErrorsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Error Message"))
        item = self.logFileTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.logFileTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source"))
        item = self.logFileTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cleansing Status"))
        item = self.logFileTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Validation Status"))
        item = self.logFileTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ingestion Status"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.LogFileConfiguration), _translate("MainWindow", "Log File Config"))
        self.LogEntryLabel.setText(_translate("MainWindow", "Log Entry Configuration"))
        self.LogEntryFilterBut.setText(_translate("MainWindow", "Filter"))
        self.LogEntryTable.setSortingEnabled(True)
        item = self.LogEntryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "List Number"))
        item = self.LogEntryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Log Entry Timestamp"))
        item = self.LogEntryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Log Entry Event"))
        item = self.LogEntryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Vector"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.LogEntryConfiguration), _translate("MainWindow", "Log Entry Config"))
        self.VectorConfigLabel.setText(_translate("MainWindow", "Vector Configuration"))
        self.VectorConfigAddVectorBut.setText(_translate("MainWindow", "Add Vector"))
        self.VectorConfigDeleteVectorBut.setText(_translate("MainWindow", "Delete Vector"))
        self.VectorConfigEditVectorBut.setText(_translate("MainWindow", "Edit Vector"))
        self.VectorConfigTable.setSortingEnabled(True)
        item = self.VectorConfigTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Selected"))
        item = self.VectorConfigTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector Name"))
        item = self.VectorConfigTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vector Description"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.VectorConfiguration), _translate("MainWindow", "Vector Config"))
        self.VectoDBPullBut.setText(_translate("MainWindow", "Pull"))
        self.VectorDBchangesTable.setSortingEnabled(True)
        item = self.VectorDBchangesTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBchangesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source IP"))
        item = self.VectorDBchangesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Request Timestamp"))
        item = self.VectorDBchangesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.VectorDBchangesTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        item = self.VectorDBchangesTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.VectorDBchangesTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Graph"))
        item = self.VectorDBchangesTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sync Status"))
        __sortingEnabled = self.VectorDBchangesTable.isSortingEnabled()
        self.VectorDBchangesTable.setSortingEnabled(False)
        self.VectorDBchangesTable.setSortingEnabled(__sortingEnabled)
        self.VectorDBApprovalLabel.setText(_translate("MainWindow", "Approval Sync"))
        self.VectorDBPushTable.setSortingEnabled(True)
        item = self.VectorDBPushTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPushTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector"))
        item = self.VectorDBPushTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.VectorDBPushTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Graph"))
        __sortingEnabled = self.VectorDBPushTable.isSortingEnabled()
        self.VectorDBPushTable.setSortingEnabled(False)
        self.VectorDBPushTable.setSortingEnabled(__sortingEnabled)
        self.VectorDBPushedVecLabel.setText(_translate("MainWindow", "Pushed Vector DB Table"))
        self.VectoDBPushBut.setText(_translate("MainWindow", "Push"))
        self.VectorDBCommitBut.setText(_translate("MainWindow", "Commit"))
        self.VectorDBPulledVecLabel.setText(_translate("MainWindow", "Pulled Vector DB Table"))
        self.VectorDBPullTable.setSortingEnabled(True)
        item = self.VectorDBPullTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.VectorDBPullTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector"))
        item = self.VectorDBPullTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.VectorDBPullTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Graph"))
        __sortingEnabled = self.VectorDBPullTable.isSortingEnabled()
        self.VectorDBPullTable.setSortingEnabled(False)
        self.VectorDBPullTable.setSortingEnabled(__sortingEnabled)
        self.VectorDBConnectionLabel.setText(_translate("MainWindow", "Connection Status to Lead: "))
        self.Tabs.setTabText(self.Tabs.indexOf(self.VectorDB), _translate("MainWindow", "Vector DB"))
        self.RelationshipConfigLabel.setText(_translate("MainWindow", "Relationship Configuration"))
        self.RelationConfigTable.setSortingEnabled(True)
        item = self.RelationConfigTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RelationConfigTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Relationship ID"))
        item = self.RelationConfigTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Parent"))
        item = self.RelationConfigTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Child"))
        item = self.RelationConfigTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Label"))
        __sortingEnabled = self.RelationConfigTable.isSortingEnabled()
        self.RelationConfigTable.setSortingEnabled(False)
        self.RelationConfigTable.setSortingEnabled(__sortingEnabled)
        self.Tabs.setTabText(self.Tabs.indexOf(self.RelConfig), _translate("MainWindow", "Relation Config"))
#<<<<<<< HEAD
        #self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/graph/graph.png\"/></p></body></html>"))
#=======
#        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"PICK\GUI_Subsystem\graph.png\"/></p></body></html>"))
#>>>>>>> 5d6a33d29f138ded66540b244976a1cf3c9dbe16
        self.GraphViewNodesLabel.setText(_translate("MainWindow", "Nodes configuration in graphical format"))
        self.GraphViewTimeLineOption.setItemText(0, _translate("MainWindow", "Option1"))
        self.GraphViewTimeLineOption.setItemText(1, _translate("MainWindow", "Option 2"))
        self.GraphViewVectorOptions.setItemText(0, _translate("MainWindow", "Option1"))
        self.GraphViewVectorOptions.setItemText(1, _translate("MainWindow", "Option 2"))
        self.GraphViewAddNodeBut.setText(_translate("MainWindow", "Add Node"))
        self.GraphViewAddRelationshipBut.setText(_translate("MainWindow", "Add Relationship"))
        self.GraphViewEditNodeBut.setText(_translate("MainWindow", "Edit node"))
        self.GraphViewGraphConfigLabel.setText(_translate("MainWindow", "Graph Configuration"))
        self.GraphViewDeleteNodeBut.setText(_translate("MainWindow", "Delete Node"))
        self.GraphViewRemRelationshipBut.setText(_translate("MainWindow", "Remove Relationship"))
        self.GraphViewIconConfigBut.setText(_translate("MainWindow", "Icon Config"))
        self.GraphViewIntervalOptions.setItemText(0, _translate("MainWindow", "Option1"))
        self.GraphViewIntervalOptions.setItemText(1, _translate("MainWindow", "Option 2"))
        self.GraphViewTimelineLabel.setText(_translate("MainWindow", "TimeLine Orientation"))
        self.GraphViewZoomOutBut.setText(_translate("MainWindow", "Zoom Out"))
        self.GraphViewDescriptionLabel.setText(_translate("MainWindow", "Description"))
        self.GraphViewEditRelationshipBut.setText(_translate("MainWindow", "Edit Relationship"))
        self.GraphViewIntervalLabel.setText(_translate("MainWindow", "Interval Units"))
        self.GraphViewVectorLabel.setText(_translate("MainWindow", "Vector"))
        self.GraphViewZoomInBut.setText(_translate("MainWindow", "Zoom In"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.GraphView), _translate("MainWindow", "Graph View"))
        self.TableViewLabel.setText(_translate("MainWindow", "Nodes Configuration in tabular format"))
        self.TableViewTable.setSortingEnabled(True)
        item = self.TableViewTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.TableViewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node Property Visibility"))
        item = self.TableViewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node ID"))
        item = self.TableViewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node Name"))
        item = self.TableViewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Node Timestamp"))
        item = self.TableViewTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Node Description"))
        item = self.TableViewTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Log Entry Reference"))
        item = self.TableViewTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Log Creator"))
        item = self.TableViewTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Event Type"))
        item = self.TableViewTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Icon Type"))
        item = self.TableViewTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Source"))
        item = self.TableViewTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Node Visibility"))
        # Table information

        item = self.TableViewTable.item(1, 1)
        item.setText("001")
        item = self.TableViewTable.item(1, 2)
        item.setText("SQL attack")
        item = self.TableViewTable.item(1, 3)
        item.setText("10:22 11/22/20 AM")
        item = self.TableViewTable.item(1, 4)
        item.setText("Red Team eng...")
        item = self.TableViewTable.item(1, 5)
        item.setText("/usr/Home/...")
        item = self.TableViewTable.item(1, 6)
        item.setText("White")
        item = self.TableViewTable.item(1, 7)
        item.setText("Red")
        item = self.TableViewTable.item(1, 8)
        item.setText("/usr/Home...")
        item = self.TableViewTable.item(1, 9)
        item.setText("log001")
        item = self.TableViewTable.item(1, 10)
        item.setText("ON")

        item = self.TableViewTable.item(2, 1)
        item.setText("002")
        item = self.TableViewTable.item(2, 2)
        item.setText("Defensive maneuver")
        item = self.TableViewTable.item(2, 3)
        item.setText("14:22 11/30/20 PM")
        item = self.TableViewTable.item(2, 4)
        item.setText("Blue Team engaging in ...")
        item = self.TableViewTable.item(2, 5)
        item.setText("/usr/Home/Documents...")
        item = self.TableViewTable.item(2, 6)
        item.setText("White")
        item = self.TableViewTable.item(2, 7)
        item.setText("Red")
        item = self.TableViewTable.item(2, 8)
        item.setText("/usr/Home...")
        item = self.TableViewTable.item(2, 9)
        item.setText("log002")
        item = self.TableViewTable.item(2, 10)
        item.setText("ON")

        __sortingEnabled = self.TableViewTable.isSortingEnabled()
        self.TableViewTable.setSortingEnabled(False)
        self.TableViewTable.setSortingEnabled(__sortingEnabled)
        self.Tabs.setTabText(self.Tabs.indexOf(self.TableView), _translate("MainWindow", "Table View"))
        self.DoubleViewVectorLabel.setText(_translate("MainWindow", "Vector"))
#<<<<<<< HEAD
        #self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/graph/graph.png\"/></p></body></html>"))
#=======
#        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"PICK\GUI_Subsystem\graph.png\"/></p></body></html>"))
#>>>>>>> 5d6a33d29f138ded66540b244976a1cf3c9dbe16
        self.DoubleViewZoomInBut.setText(_translate("MainWindow", "Zoom In"))
        self.DoubleViewIntervalOptions.setItemText(0, _translate("MainWindow", "Option1"))
        self.DoubleViewIntervalOptions.setItemText(1, _translate("MainWindow", "Option 2"))
        self.DoubleViewEditRelationshipBut.setText(_translate("MainWindow", "Edit Relationship"))
        self.DoubleViewZoomOutBut.setText(_translate("MainWindow", "Zoom Out"))
        self.DoubleViewIntervalUnitsLabel.setText(_translate("MainWindow", "Interval Units"))
        self.DoubleViewDescriptionLabel.setText(_translate("MainWindow", "Description"))
        self.DoubleViewAddRelationshipBut.setText(_translate("MainWindow", "Add Relationship"))
        self.DoubleViewIconConfigBut.setText(_translate("MainWindow", "Icon Config"))
        self.DoubleViewTable.setSortingEnabled(True)
        item = self.DoubleViewTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.DoubleViewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node Property Visibility"))
        item = self.DoubleViewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node ID"))
        item = self.DoubleViewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node Name"))
        item = self.DoubleViewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Node Timestamp"))
        item = self.DoubleViewTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Node Description"))
        item = self.DoubleViewTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Log Entry Reference"))
        item = self.DoubleViewTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Log Creator"))
        item = self.DoubleViewTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Event Type"))
        item = self.DoubleViewTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Icon Type"))
        item = self.DoubleViewTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Source"))
        item = self.DoubleViewTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Node Visibility"))

        item = self.DoubleViewTable.item(1, 1)
        item.setText("001")
        item = self.DoubleViewTable.item(1, 2)
        item.setText("SQL attack")
        item = self.DoubleViewTable.item(1, 3)
        item.setText("10:22 11/22/20 AM")
        item = self.DoubleViewTable.item(1, 4)
        item.setText("Red Team eng...")
        item = self.DoubleViewTable.item(1, 5)
        item.setText("/usr/Home/...")
        item = self.DoubleViewTable.item(1, 6)
        item.setText("White")
        item = self.DoubleViewTable.item(1, 7)
        item.setText("Red")
        item = self.DoubleViewTable.item(1, 8)
        item.setText("/usr/Home...")
        item = self.DoubleViewTable.item(1, 9)
        item.setText("log001")
        item = self.DoubleViewTable.item(1, 10)
        item.setText("ON")

        item = self.DoubleViewTable.item(2, 1)
        item.setText("002")
        item = self.DoubleViewTable.item(2, 2)
        item.setText("Defensive maneuver")
        item = self.DoubleViewTable.item(2, 3)
        item.setText("14:22 11/30/20 PM")
        item = self.DoubleViewTable.item(2, 4)
        item.setText("Blue Team engaging in ...")
        item = self.DoubleViewTable.item(2, 5)
        item.setText("/usr/Home/Documents...")
        item = self.DoubleViewTable.item(2, 6)
        item.setText("White")
        item = self.DoubleViewTable.item(2, 7)
        item.setText("Red")
        item = self.DoubleViewTable.item(2, 8)
        item.setText("/usr/Home...")
        item = self.DoubleViewTable.item(2, 9)
        item.setText("log002")
        item = self.DoubleViewTable.item(2, 10)
        item.setText("ON")


        __sortingEnabled = self.DoubleViewTable.isSortingEnabled()
        self.DoubleViewTable.setSortingEnabled(False)
        self.DoubleViewTable.setSortingEnabled(__sortingEnabled)
        self.GraphConfi.setText(_translate("MainWindow", "Graph Configuration"))
        self.DoubleViewVectorOptions.setItemText(0, _translate("MainWindow", "Option1"))
        self.DoubleViewVectorOptions.setItemText(1, _translate("MainWindow", "Option 2"))
        self.DoubleViewTimelineOptions.setItemText(0, _translate("MainWindow", "Option1"))
        self.DoubleViewTimelineOptions.setItemText(1, _translate("MainWindow", "Option 2"))
        self.DoubleViewRemoveRelationshipBut.setText(_translate("MainWindow", "Remove Relationship"))
        self.DoubleViewEditNodeBut.setText(_translate("MainWindow", "Edit node"))
        self.DoubleViewAddNodeBut.setText(_translate("MainWindow", "Add Node"))
        self.DoubleViewTimelineLabel.setText(_translate("MainWindow", "TimeLine Orientation"))
        self.DoubleViewDeleteNodeBut.setText(_translate("MainWindow", "Delete Node"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.DoubleView), _translate("MainWindow", "Double View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Export.setTitle(_translate("MainWindow", "Export"))
        self.menuGraph_Export_Options.setTitle(_translate("MainWindow", "Graph Export Options"))
        self.menuTable_Export_Options.setTitle(_translate("MainWindow", "Table Export Options"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit/Changes"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionJPEG.setText(_translate("MainWindow", "JPEG"))
        self.actionPNG.setText(_translate("MainWindow", "PNG"))
        self.actionView_Vector.setText(_translate("MainWindow", "View Vector"))
        self.actionView_Table.setText(_translate("MainWindow", "View Table"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionChange_list.setText(_translate("MainWindow", "Change list"))
        self.actionEvent_Configuration.setText(_translate("MainWindow", "Event Configuration"))
        self.actionDir_Configuration.setText(_translate("MainWindow", "Directory Configuration"))
        self.actionTeam_Configuration.setText(_translate("MainWindow", "Team Configuration"))
        self.actionEvent_Configuration_2.setText(_translate("MainWindow", "Event Configuration"))
        self.actionPNG_2.setText(_translate("MainWindow", "PNG"))
        self.actionJPEG_2.setText(_translate("MainWindow", "JPEG"))
        self.actionCSV.setText(_translate("MainWindow", "CSV"))
        self.actionExcel.setText(_translate("MainWindow", "Excel"))
        self.actionPDF.setText(_translate("MainWindow", "PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
